source 'https://rubygems.org'

gem 'rake'
# Add your dependencies here:
gem 'ProMotion'
gem 'ProMotion-form'
gem "bubble-wrap", "~> 1.9.2", require: 'bubble-wrap/all'
gem 'afmotion'
gem 'ruby_motion_query'
